version: '3.7'
services:
  adapter:
    build:
      args:
        TARGETPLATFORM: linux/amd64
      context: .
      dockerfile: Dockerfile
    environment:
      - TARGETPLATFORM=linux/amd64
    volumes:
      - ./fanuc/adapter.ini:/adapter.ini
