version: '3.7'
services:
  adapter:
    image: strangesast/mtconnect-adapter
    network_mode: host
    ports:
      - "7878:7878"
    build:
      context: .
      args:
        VERSION: 1.0.5
        TARGETPLATFORM: linux/amd64
    environment:
      - FOCAS_SERVICE_NAME=fanuc
      - FOCAS_HOST=127.0.0.1
